/* automatically generated by rust-bindgen */

pub const __WORDSIZE: u32 = 64;
pub const __DARWIN_ONLY_64_BIT_INO_T: u32 = 0;
pub const __DARWIN_ONLY_VERS_1050: u32 = 0;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const __DARWIN_UNIX03: u32 = 1;
pub const __DARWIN_64_BIT_INO_T: u32 = 1;
pub const __DARWIN_VERS_1050: u32 = 1;
pub const __DARWIN_NON_CANCELABLE: u32 = 0;
pub const __DARWIN_SUF_64_BIT_INO_T: &'static [u8; 9usize] = b"$INODE64\0";
pub const __DARWIN_SUF_1050: &'static [u8; 6usize] = b"$1050\0";
pub const __DARWIN_SUF_EXTSN: &'static [u8; 14usize] = b"$DARWIN_EXTSN\0";
pub const __DARWIN_C_ANSI: u32 = 4096;
pub const __DARWIN_C_FULL: u32 = 900000;
pub const __DARWIN_C_LEVEL: u32 = 900000;
pub const __STDC_WANT_LIB_EXT1__: u32 = 1;
pub const __DARWIN_NO_LONG_LONG: u32 = 0;
pub const _DARWIN_FEATURE_64_BIT_INODE: u32 = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: u32 = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: u32 = 3;
pub const __PTHREAD_SIZE__: u32 = 8176;
pub const __PTHREAD_ATTR_SIZE__: u32 = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: u32 = 8;
pub const __PTHREAD_MUTEX_SIZE__: u32 = 56;
pub const __PTHREAD_CONDATTR_SIZE__: u32 = 8;
pub const __PTHREAD_COND_SIZE__: u32 = 40;
pub const __PTHREAD_ONCE_SIZE__: u32 = 8;
pub const __PTHREAD_RWLOCK_SIZE__: u32 = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: u32 = 16;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const INT64_MAX: u64 = 9223372036854775807;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT64_MIN: i64 = -9223372036854775808;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const UINT64_MAX: i32 = -1;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST64_MIN: i64 = -9223372036854775808;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const INT_LEAST64_MAX: u64 = 9223372036854775807;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const UINT_LEAST64_MAX: i32 = -1;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -32768;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST64_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 32767;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const INT_FAST64_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 65535;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const UINT_FAST64_MAX: i32 = -1;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const UINTPTR_MAX: i32 = -1;
pub const INTMAX_MIN: i64 = -9223372036854775808;
pub const INTMAX_MAX: u64 = 9223372036854775807;
pub const UINTMAX_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIZE_MAX: i32 = -1;
pub const RSIZE_MAX: i32 = -1;
pub const WINT_MIN: i32 = -2147483648;
pub const WINT_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub const SASI_INFINITE: u32 = 4294967295;
pub const SASI_SUCCESS: u32 = 0;
pub const SASI_FAIL: u32 = 1;
pub const SASI_1K_SIZE_IN_BYTES: u32 = 1024;
pub const SASI_BITS_IN_BYTE: u32 = 8;
pub const SASI_BITS_IN_32BIT_WORD: u32 = 32;
pub const SASI_OK: u32 = 0;
pub const SASI_MAX_UINT32_VAL: u32 = 4294967295;
pub const CRYS_ERROR_BASE: u32 = 15728640;
pub const CRYS_ERROR_LAYER_RANGE: u32 = 65536;
pub const CRYS_ERROR_MODULE_RANGE: u32 = 256;
pub const CRYS_LAYER_ERROR_IDX: u32 = 0;
pub const LLF_LAYER_ERROR_IDX: u32 = 1;
pub const GENERIC_ERROR_IDX: u32 = 5;
pub const AES_ERROR_IDX: u32 = 0;
pub const DES_ERROR_IDX: u32 = 1;
pub const HASH_ERROR_IDX: u32 = 2;
pub const HMAC_ERROR_IDX: u32 = 3;
pub const RSA_ERROR_IDX: u32 = 4;
pub const DH_ERROR_IDX: u32 = 5;
pub const ECPKI_ERROR_IDX: u32 = 8;
pub const RND_ERROR_IDX: u32 = 12;
pub const COMMON_ERROR_IDX: u32 = 13;
pub const KDF_ERROR_IDX: u32 = 17;
pub const HKDF_ERROR_IDX: u32 = 18;
pub const AESCCM_ERROR_IDX: u32 = 21;
pub const FIPS_ERROR_IDX: u32 = 23;
pub const PKA_MODULE_ERROR_IDX: u32 = 33;
pub const CHACHA_ERROR_IDX: u32 = 34;
pub const EC_MONT_EDW_ERROR_IDX: u32 = 35;
pub const CHACHA_POLY_ERROR_IDX: u32 = 36;
pub const POLY_ERROR_IDX: u32 = 37;
pub const SRP_ERROR_IDX: u32 = 38;
pub const CRYS_AES_MODULE_ERROR_BASE: u32 = 15728640;
pub const CRYS_DES_MODULE_ERROR_BASE: u32 = 15728896;
pub const CRYS_HASH_MODULE_ERROR_BASE: u32 = 15729152;
pub const CRYS_HMAC_MODULE_ERROR_BASE: u32 = 15729408;
pub const CRYS_RSA_MODULE_ERROR_BASE: u32 = 15729664;
pub const CRYS_DH_MODULE_ERROR_BASE: u32 = 15729920;
pub const CRYS_ECPKI_MODULE_ERROR_BASE: u32 = 15730688;
pub const LLF_ECPKI_MODULE_ERROR_BASE: u32 = 15796224;
pub const CRYS_RND_MODULE_ERROR_BASE: u32 = 15731712;
pub const LLF_RND_MODULE_ERROR_BASE: u32 = 15797248;
pub const CRYS_COMMON_MODULE_ERROR_BASE: u32 = 15731968;
pub const CRYS_KDF_MODULE_ERROR_BASE: u32 = 15732992;
pub const CRYS_HKDF_MODULE_ERROR_BASE: u32 = 15733248;
pub const CRYS_AESCCM_MODULE_ERROR_BASE: u32 = 15734016;
pub const CRYS_FIPS_MODULE_ERROR_BASE: u32 = 15734528;
pub const PKA_MODULE_ERROR_BASE: u32 = 15737088;
pub const CRYS_CHACHA_MODULE_ERROR_BASE: u32 = 15737344;
pub const CRYS_CHACHA_POLY_MODULE_ERROR_BASE: u32 = 15737856;
pub const CRYS_POLY_MODULE_ERROR_BASE: u32 = 15738112;
pub const CRYS_SRP_MODULE_ERROR_BASE: u32 = 15738368;
pub const CRYS_EC_MONT_EDW_MODULE_ERROR_BASE: u32 = 15737600;
pub const GENERIC_ERROR_BASE: u32 = 16056320;
pub const CRYS_FATAL_ERROR: u32 = 16056320;
pub const CRYS_OUT_OF_RESOURCE_ERROR: u32 = 16056321;
pub const CRYS_ILLEGAL_RESOURCE_VAL_ERROR: u32 = 16056322;
pub const CRYS_OK: u32 = 0;
pub const NRF_CC310_BL_ECDSA_CONTEXT_INITIALIZED: u32 = 3148502493;
pub const NRF_CC310_BL_ECDSA_VERIFY_CONTEXT_SIZE_SECP224R1: u32 = 140;
pub const NRF_CC310_BL_ECDSA_VERIFY_CONTEXT_SIZE_SECP256R1: u32 = 160;
pub const NRF_CC310_BL_HASH_CONTEXT_INITIALIZED: u32 = 3148502493;
pub const NRF_CC310_BL_HASH_CONTEXT_BUFFER_SIZE_SHA256: u32 = 112;
pub const NRF_CC310_BL_SHA256_DIGEST_SIZE_IN_WORDS: u32 = 8;
pub const NRF_CC310_BL_SHA256_DIGEST_SIZE_IN_BYTES: u32 = 32;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
    _bindgen_union_align: [u64; 16usize],
}
#[test]
fn bindgen_test_layout___mbstate_t() {
    assert_eq!(
        ::std::mem::size_of::<__mbstate_t>(),
        128usize,
        concat!("Size of: ", stringify!(__mbstate_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__mbstate_t>(),
        8usize,
        concat!("Alignment of ", stringify!(__mbstate_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__mbstate_t>())).__mbstate8 as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__mbstate_t),
            "::",
            stringify!(__mbstate8)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__mbstate_t>()))._mbstateL as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__mbstate_t),
            "::",
            stringify!(_mbstateL)
        )
    );
}
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
#[test]
fn bindgen_test_layout___darwin_pthread_handler_rec() {
    assert_eq!(
        ::std::mem::size_of::<__darwin_pthread_handler_rec>(),
        24usize,
        concat!("Size of: ", stringify!(__darwin_pthread_handler_rec))
    );
    assert_eq!(
        ::std::mem::align_of::<__darwin_pthread_handler_rec>(),
        8usize,
        concat!("Alignment of ", stringify!(__darwin_pthread_handler_rec))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<__darwin_pthread_handler_rec>())).__routine as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__darwin_pthread_handler_rec),
            "::",
            stringify!(__routine)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<__darwin_pthread_handler_rec>())).__arg as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__darwin_pthread_handler_rec),
            "::",
            stringify!(__arg)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<__darwin_pthread_handler_rec>())).__next as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__darwin_pthread_handler_rec),
            "::",
            stringify!(__next)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_attr_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_attr_t>(),
        64usize,
        concat!("Size of: ", stringify!(_opaque_pthread_attr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_attr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_attr_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_attr_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_attr_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_attr_t>())).__opaque as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_attr_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_cond_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_cond_t>(),
        48usize,
        concat!("Size of: ", stringify!(_opaque_pthread_cond_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_cond_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_cond_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_cond_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_cond_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_cond_t>())).__opaque as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_cond_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_condattr_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_condattr_t>(),
        16usize,
        concat!("Size of: ", stringify!(_opaque_pthread_condattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_condattr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_condattr_t))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_condattr_t>())).__sig as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_condattr_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_condattr_t>())).__opaque as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_condattr_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_mutex_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_mutex_t>(),
        64usize,
        concat!("Size of: ", stringify!(_opaque_pthread_mutex_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_mutex_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_mutex_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_mutex_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_mutex_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_mutex_t>())).__opaque as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_mutex_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_mutexattr_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_mutexattr_t>(),
        16usize,
        concat!("Size of: ", stringify!(_opaque_pthread_mutexattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_mutexattr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_mutexattr_t))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_mutexattr_t>())).__sig as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_mutexattr_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_mutexattr_t>())).__opaque as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_mutexattr_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_once_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_once_t>(),
        16usize,
        concat!("Size of: ", stringify!(_opaque_pthread_once_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_once_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_once_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_once_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_once_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_once_t>())).__opaque as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_once_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_rwlock_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_rwlock_t>(),
        200usize,
        concat!("Size of: ", stringify!(_opaque_pthread_rwlock_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_rwlock_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_rwlock_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_rwlock_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_rwlock_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_rwlock_t>())).__opaque as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_rwlock_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_rwlockattr_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_rwlockattr_t>(),
        24usize,
        concat!("Size of: ", stringify!(_opaque_pthread_rwlockattr_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_rwlockattr_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_rwlockattr_t))
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_rwlockattr_t>())).__sig as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_rwlockattr_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_rwlockattr_t>())).__opaque as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_rwlockattr_t),
            "::",
            stringify!(__opaque)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
#[test]
fn bindgen_test_layout__opaque_pthread_t() {
    assert_eq!(
        ::std::mem::size_of::<_opaque_pthread_t>(),
        8192usize,
        concat!("Size of: ", stringify!(_opaque_pthread_t))
    );
    assert_eq!(
        ::std::mem::align_of::<_opaque_pthread_t>(),
        8usize,
        concat!("Alignment of ", stringify!(_opaque_pthread_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_t>())).__sig as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_t),
            "::",
            stringify!(__sig)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<_opaque_pthread_t>())).__cleanup_stack as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_t),
            "::",
            stringify!(__cleanup_stack)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<_opaque_pthread_t>())).__opaque as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_opaque_pthread_t),
            "::",
            stringify!(__opaque)
        )
    );
}
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type u_int8_t = ::std::os::raw::c_uchar;
pub type u_int16_t = ::std::os::raw::c_ushort;
pub type u_int32_t = ::std::os::raw::c_uint;
pub type u_int64_t = ::std::os::raw::c_ulonglong;
pub type register_t = i64;
pub type user_addr_t = u_int64_t;
pub type user_size_t = u_int64_t;
pub type user_ssize_t = i64;
pub type user_long_t = i64;
pub type user_ulong_t = u_int64_t;
pub type user_time_t = i64;
pub type user_off_t = i64;
pub type syscall_arg_t = u_int64_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
pub type rsize_t = ::std::os::raw::c_ulong;
pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = f64;
pub type SaSiVirtAddr_t = usize;
pub type SaSiBool_t = u32;
pub type SaSiStatus = u32;
#[doc = " Boolean false definition."]
pub const SaSiBool_SASI_FALSE: SaSiBool = 0;
#[doc = " Boolean true definition."]
pub const SaSiBool_SASI_TRUE: SaSiBool = 1;
#[doc = " Boolean definition."]
pub type SaSiBool = u32;
#[doc = " The typedef definition of all of the error codes that are returned from the CRYS functions"]
pub type CRYSError_t = u32;
extern "C" {
    #[doc = "@file"]
    #[doc = ""]
    #[doc = " @addtogroup nrf_cc310_bl"]
    #[doc = " @{"]
    #[doc = " @brief Function for initializing the CC310 hardware and runtime library."]
    #[doc = ""]
    #[doc = " @note    Running this initialization is intended for cases where there"]
    #[doc = "          is no direct requirement for the RNG subsystem (all operations are deterministic)."]
    #[doc = ""]
    #[doc = " @retval  CRYS_OK     Initialization was successful."]
    #[link_name = "\u{1}_nrf_cc310_bl_init"]
    pub fn nrf_cc310_bl_init() -> CRYSError_t;
}
#[doc = "@brief Structure holding the secp256r1 public key represented by X,Y coordinates."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrf_cc310_bl_ecc_public_key_secp256r1_t {
    #[doc = "!< Public key X coordinate in big-endian format."]
    pub x: [u8; 32usize],
    #[doc = "!< Public key Y coordinate in big-endian format."]
    pub y: [u8; 32usize],
}
#[test]
fn bindgen_test_layout_nrf_cc310_bl_ecc_public_key_secp256r1_t() {
    assert_eq!(
        ::std::mem::size_of::<nrf_cc310_bl_ecc_public_key_secp256r1_t>(),
        64usize,
        concat!(
            "Size of: ",
            stringify!(nrf_cc310_bl_ecc_public_key_secp256r1_t)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<nrf_cc310_bl_ecc_public_key_secp256r1_t>(),
        1usize,
        concat!(
            "Alignment of ",
            stringify!(nrf_cc310_bl_ecc_public_key_secp256r1_t)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecc_public_key_secp256r1_t>())).x as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecc_public_key_secp256r1_t),
            "::",
            stringify!(x)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecc_public_key_secp256r1_t>())).y as *const _
                as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecc_public_key_secp256r1_t),
            "::",
            stringify!(y)
        )
    );
}
#[doc = "@brief Structure holding the secp256r1 signature represented by R,S values."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nrf_cc310_bl_ecc_signature_secp256r1_t {
    #[doc = "!< Signature R part in big-endian format."]
    pub r: [u8; 32usize],
    #[doc = "!< Signature S part in big-endian format."]
    pub s: [u8; 32usize],
}
#[test]
fn bindgen_test_layout_nrf_cc310_bl_ecc_signature_secp256r1_t() {
    assert_eq!(
        ::std::mem::size_of::<nrf_cc310_bl_ecc_signature_secp256r1_t>(),
        64usize,
        concat!(
            "Size of: ",
            stringify!(nrf_cc310_bl_ecc_signature_secp256r1_t)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<nrf_cc310_bl_ecc_signature_secp256r1_t>(),
        1usize,
        concat!(
            "Alignment of ",
            stringify!(nrf_cc310_bl_ecc_signature_secp256r1_t)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecc_signature_secp256r1_t>())).r as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecc_signature_secp256r1_t),
            "::",
            stringify!(r)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecc_signature_secp256r1_t>())).s as *const _
                as usize
        },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecc_signature_secp256r1_t),
            "::",
            stringify!(s)
        )
    );
}
#[doc = "@brief Structure holding memory required for allocation of CC310 ECDSA verify context"]
#[doc = "        using curve secp256r1."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nrf_cc310_bl_ecdsa_verify_context_secp256r1_t {
    pub init_val: u32,
    pub context_buffer: [u8; 160usize],
}
#[test]
fn bindgen_test_layout_nrf_cc310_bl_ecdsa_verify_context_secp256r1_t() {
    assert_eq!(
        ::std::mem::size_of::<nrf_cc310_bl_ecdsa_verify_context_secp256r1_t>(),
        164usize,
        concat!(
            "Size of: ",
            stringify!(nrf_cc310_bl_ecdsa_verify_context_secp256r1_t)
        )
    );
    assert_eq!(
        ::std::mem::align_of::<nrf_cc310_bl_ecdsa_verify_context_secp256r1_t>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(nrf_cc310_bl_ecdsa_verify_context_secp256r1_t)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecdsa_verify_context_secp256r1_t>())).init_val
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecdsa_verify_context_secp256r1_t),
            "::",
            stringify!(init_val)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_ecdsa_verify_context_secp256r1_t>())).context_buffer
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_ecdsa_verify_context_secp256r1_t),
            "::",
            stringify!(context_buffer)
        )
    );
}
extern "C" {
    #[doc = "@brief Function for initializing the context information for an ECDSA verify operation."]
    #[doc = ""]
    #[doc = " @note    The memory that holds the context object must be allocated prior to this call."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_context       Pointer to the structure holding context information"]
    #[doc = "                                  for the ECDSA verify operation."]
    #[doc = " @param[in]       p_public_key    Pointer to the structure holding the public key for"]
    #[doc = "                                  the ECDSA verify operation."]
    #[doc = ""]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_USER_CONTEXT_PTR_ERROR        p_context was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_SIGNER_PUBL_KEY_VALIDATION_TAG_ERROR  p_public_key was NULL."]
    #[link_name = "\u{1}_nrf_cc310_bl_ecdsa_verify_init_secp256r1"]
    pub fn nrf_cc310_bl_ecdsa_verify_init_secp256r1(
        p_context: *mut nrf_cc310_bl_ecdsa_verify_context_secp256r1_t,
        p_public_key: *const nrf_cc310_bl_ecc_public_key_secp256r1_t,
    ) -> CRYSError_t;
}
extern "C" {
    #[doc = "@brief Function for executing an ECDSA verify operation using secp256r1 with hash input."]
    #[doc = ""]
    #[doc = " @note    The ECDSA verify context structure must be initialized prior to this call using"]
    #[doc = "          @ref nrf_cc310_bl_ecdsa_verify_init_secp256r1."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_context   Pointer to the structure holding context information"]
    #[doc = "                              for the ECDSA verify operation."]
    #[doc = " @param[in]       p_signature Pointer to the structure holding the signature to use for"]
    #[doc = "                              the ECDSA verify operation."]
    #[doc = " @param[in]       p_hash      Pointer to the hash to use in the ECDSA verify operation."]
    #[doc = " @param[in]       hash_len    Length of the hash to verify."]
    #[doc = ""]
    #[doc = " @retval CRYS_OK Signature was successfully verified."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_USER_CONTEXT_PTR_ERROR     p_context was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_USER_CONTEXT_VALIDATION_TAG_ERROR  p_context was not initialized."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_SIGNATURE_IN_PTR_ERROR     p_signature was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_MESSAGE_DATA_IN_PTR_ERROR  p_hash was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_MESSAGE_DATA_IN_SIZE_ERROR hash_len was invalid."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INCONSISTENT_VERIFY_ERROR          Signature verification failed."]
    #[link_name = "\u{1}_nrf_cc310_bl_ecdsa_verify_hash_secp256r1"]
    pub fn nrf_cc310_bl_ecdsa_verify_hash_secp256r1(
        p_context: *mut nrf_cc310_bl_ecdsa_verify_context_secp256r1_t,
        p_signature: *const nrf_cc310_bl_ecc_signature_secp256r1_t,
        p_hash: *const u8,
        hash_len: u32,
    ) -> CRYSError_t;
}
extern "C" {
    #[doc = "@brief Function for executing an ECDSA verify operation using secp256r1 with"]
    #[doc = "                                  hash input in integrated form."]
    #[doc = ""]
    #[doc = " @note This will run initialization of ECDSA context and run ECDSA verify in a single step."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_context       Pointer to the structure holding context information for"]
    #[doc = "                                  the ECDSA verify operation."]
    #[doc = " @param[in]       p_public_key    Pointer to the structure holding the public key for"]
    #[doc = "                                  the ECDSA verify operation."]
    #[doc = " @param[in]       p_signature     Pointer to the structure holding the signature to use"]
    #[doc = "                                  for the ECDSA verify operation."]
    #[doc = " @param[in]       p_hash          Pointer to the hash to use in the ECDSA verify operation."]
    #[doc = " @param[in]       hash_len        Length of the hash to verify."]
    #[doc = ""]
    #[doc = " @retval CRYS_OK Signature was successfully verified."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_USER_CONTEXT_PTR_ERROR     p_context was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_USER_CONTEXT_VALIDATION_TAG_ERROR  p_context was not initialized."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_SIGNER_PUBL_KEY_VALIDATION_TAG_ERROR"]
    #[doc = "         p_public_key was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_SIGNATURE_IN_PTR_ERROR     p_signature was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_MESSAGE_DATA_IN_PTR_ERROR  p_hash was NULL."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INVALID_MESSAGE_DATA_IN_SIZE_ERROR hash_len was invalid."]
    #[doc = " @retval CRYS_ECDSA_VERIFY_INCONSISTENT_VERIFY_ERROR          Signature verification failed."]
    #[link_name = "\u{1}_nrf_cc310_bl_ecdsa_verify_secp256r1"]
    pub fn nrf_cc310_bl_ecdsa_verify_secp256r1(
        p_context: *mut nrf_cc310_bl_ecdsa_verify_context_secp256r1_t,
        p_public_key: *const nrf_cc310_bl_ecc_public_key_secp256r1_t,
        p_signature: *const nrf_cc310_bl_ecc_signature_secp256r1_t,
        p_hash: *const u8,
        hash_len: u32,
    ) -> CRYSError_t;
}
#[doc = "@brief Structure to hold SHA-256 context information."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct nrf_cc310_bl_hash_context_sha256_t {
    pub init_val: u32,
    pub context_buffer: [u8; 112usize],
}
#[test]
fn bindgen_test_layout_nrf_cc310_bl_hash_context_sha256_t() {
    assert_eq!(
        ::std::mem::size_of::<nrf_cc310_bl_hash_context_sha256_t>(),
        116usize,
        concat!("Size of: ", stringify!(nrf_cc310_bl_hash_context_sha256_t))
    );
    assert_eq!(
        ::std::mem::align_of::<nrf_cc310_bl_hash_context_sha256_t>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(nrf_cc310_bl_hash_context_sha256_t)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_hash_context_sha256_t>())).init_val as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_hash_context_sha256_t),
            "::",
            stringify!(init_val)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<nrf_cc310_bl_hash_context_sha256_t>())).context_buffer
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nrf_cc310_bl_hash_context_sha256_t),
            "::",
            stringify!(context_buffer)
        )
    );
}
#[doc = "@brief Array to hold SHA-256 hash digest."]
pub type nrf_cc310_bl_hash_digest_sha256_t = [u8; 32usize];
extern "C" {
    #[doc = "@brief Function for initializing the SHA-256 context."]
    #[doc = ""]
    #[doc = " @note Memory pointed to in hash context must be allocated prior to this call."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_hash_context  Structure holding context information for"]
    #[doc = "                                  the SHA-256 operation."]
    #[doc = ""]
    #[doc = " @retval CRYS_OK If call was successful."]
    #[doc = " @retval  CRYS_HASH_INVALID_USER_CONTEXT_POINTER_ERROR    p_hash_context was NULL."]
    #[link_name = "\u{1}_nrf_cc310_bl_hash_sha256_init"]
    pub fn nrf_cc310_bl_hash_sha256_init(
        p_hash_context: *mut nrf_cc310_bl_hash_context_sha256_t,
    ) -> CRYSError_t;
}
extern "C" {
    #[doc = " @brief Function for running an update to the SHA-256 hash calculation."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_hash_context  Structure holding context information"]
    #[doc = "                                  for the SHA-256 operation."]
    #[doc = ""]
    #[doc = " @retval CRYS_OK If call was successful."]
    #[doc = " @retval CRYS_HASH_INVALID_USER_CONTEXT_POINTER_ERROR    p_hash_context was NULL."]
    #[doc = " @retval CRYS_HASH_USER_CONTEXT_CORRUPTED_ERROR          p_hash_context not initialized."]
    #[doc = " @retval CRYS_HASH_LAST_BLOCK_ALREADY_PROCESSED_ERROR    p_hash_context already finalized."]
    #[link_name = "\u{1}_nrf_cc310_bl_hash_sha256_update"]
    pub fn nrf_cc310_bl_hash_sha256_update(
        p_hash_context: *mut nrf_cc310_bl_hash_context_sha256_t,
        p_src: *const u8,
        len: u32,
    ) -> CRYSError_t;
}
extern "C" {
    #[doc = " @brief Function for finalizing the hash calculation."]
    #[doc = ""]
    #[doc = "  @note Memory pointed to in hash digest must be allocated prior to this call."]
    #[doc = ""]
    #[doc = " @param[in,out]   p_hash_context  Structure holding context information for"]
    #[doc = "                                  the SHA-256 operation."]
    #[doc = " @param[in,out]   p_hash_digest   Pointer to the structure holding SHA-256"]
    #[doc = "                                  hash digest. Data pointed to must be 32 bytes long."]
    #[doc = ""]
    #[doc = " @retval  CRYS_HASH_INVALID_USER_CONTEXT_POINTER_ERROR    p_hash_context was NULL."]
    #[doc = " @retval  CRYS_HASH_USER_CONTEXT_CORRUPTED_ERROR          p_hash_context was corrupted."]
    #[doc = " @retval  CRYS_HASH_INVALID_RESULT_BUFFER_POINTER_ERROR   p_digest was NULL."]
    #[link_name = "\u{1}_nrf_cc310_bl_hash_sha256_finalize"]
    pub fn nrf_cc310_bl_hash_sha256_finalize(
        p_hash_context: *mut nrf_cc310_bl_hash_context_sha256_t,
        p_digest: *mut nrf_cc310_bl_hash_digest_sha256_t,
    ) -> CRYSError_t;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout___va_list_tag() {
    assert_eq!(
        ::std::mem::size_of::<__va_list_tag>(),
        24usize,
        concat!("Size of: ", stringify!(__va_list_tag))
    );
    assert_eq!(
        ::std::mem::align_of::<__va_list_tag>(),
        8usize,
        concat!("Alignment of ", stringify!(__va_list_tag))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__va_list_tag>())).gp_offset as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__va_list_tag),
            "::",
            stringify!(gp_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__va_list_tag>())).fp_offset as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(__va_list_tag),
            "::",
            stringify!(fp_offset)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__va_list_tag>())).overflow_arg_area as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(__va_list_tag),
            "::",
            stringify!(overflow_arg_area)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__va_list_tag>())).reg_save_area as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(__va_list_tag),
            "::",
            stringify!(reg_save_area)
        )
    );
}
